const STORAGE_KEY = 'financial-lab-v3-data';
const DEFAULTS = {
  researcherName:'Rob', paycheck:0, currentBalance:0, payDate:'', nextPayday:'', savingsRate:10,
  billName:'', billDate:'', billAmount:0, saveAmount:0, debtAmount:0, debtGoal:0, expenses:0,
  customSavings:null, customDebt:null, bills:[], paycheckHistory:[], approvedPlan:null,
  missions:{spending:false,saving:false,bills:false,friday:false}, profile:{payFrequency:'weekly',paydayDay:5,incomePattern:'variable',recurringBillCount:9,financialStrategy:'balanced',reserveDays:14}, lastUpdated:''
};
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const dateAtNoon=v=>v?new Date(`${v}T12:00:00`):null;
const iso=d=>d.toISOString().slice(0,10);
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));
function load(){try{const old=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');const migratedBills=Array.isArray(old.bills)?old.bills.map((b,i)=>({id:b.id||`bill-${i}-${Date.now()}`,name:b.name||'Bill',amount:Number(b.amount)||0,dueDate:b.dueDate||b.date||'',date:b.dueDate||b.date||'',priority:b.priority||'important',frequency:b.frequency||'monthly',autopay:!!b.autopay,paidOccurrences:Array.isArray(b.paidOccurrences)?b.paidOccurrences:(b.paid&&b.date?[b.date]:[])})):[];return {...DEFAULTS,...old,bills:migratedBills,paycheckHistory:Array.isArray(old.paycheckHistory)?old.paycheckHistory:[],missions:{...DEFAULTS.missions,...(old.missions||{})},profile:{...DEFAULTS.profile,...(old.profile||{})}}}catch{return structuredClone(DEFAULTS)}}
let data=load();
const priorityRank={essential:0,important:1,flexible:2};
function billDefinitions(){return (Array.isArray(data.bills)?data.bills:[]).filter(b=>b.name||b.dueDate||b.date||Number(b.amount)).map((b,i)=>({id:b.id||`bill-${i}-${b.name||'bill'}`,name:b.name||'Bill',amount:Number(b.amount)||0,dueDate:b.dueDate||b.date||'',date:b.dueDate||b.date||'',priority:b.priority||'important',frequency:b.frequency||'monthly',autopay:!!b.autopay,paidOccurrences:Array.isArray(b.paidOccurrences)?b.paidOccurrences:[]}))}
function monthDate(year,month,day){const last=new Date(year,month+1,0,12).getDate();return new Date(year,month,Math.min(day,last),12)}
function billOccurrences(startDate,endDate){const start=new Date(startDate);start.setHours(12,0,0,0);const end=new Date(endDate);end.setHours(12,0,0,0);const out=[];for(const b of billDefinitions()){const base=dateAtNoon(b.dueDate);if(!base)continue;const paid=new Set(b.paidOccurrences||[]);const add=d=>{if(d>end)return;const key=iso(d);out.push({...b,parentId:b.id,occurrenceDate:key,date:key,paid:paid.has(key)})};if(b.frequency==='once'){if(base<=end)add(base);continue}if(b.frequency==='monthly'){const scanStart=new Date(start.getFullYear(),start.getMonth(),1,12);for(let cursor=new Date(scanStart);cursor<=end;cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1,12)){const d=monthDate(cursor.getFullYear(),cursor.getMonth(),base.getDate());if(d>=base&&d<=end)add(d)}continue}const step=b.frequency==='biweekly'?14:7;let d=new Date(base);while(d<start)d=new Date(d.getTime()+step*86400000);const prior=new Date(d.getTime()-step*86400000);if(prior>=base&&prior<start&&prior>=new Date(start.getTime()-step*86400000))add(prior);for(;d<=end;d=new Date(d.getTime()+step*86400000))add(new Date(d))}return out.sort((a,b)=>(priorityRank[a.priority]-priorityRank[b.priority])||a.date.localeCompare(b.date))}
function normalizedBills(){const today=dateAtNoon(data.payDate)||new Date();today.setHours(12,0,0,0);const horizon=new Date(today.getTime()+45*86400000);return billOccurrences(today,horizon)}
function paydaysThrough(dueDate,today,nextPay,freqDays){
  const due=dateAtNoon(dueDate);if(!due||due<=today)return 1;
  let count=1; // this paycheck
  let cursor=new Date(nextPay);
  let guard=0;
  while(cursor<=due&&guard<60){count+=1;cursor=new Date(cursor.getTime()+freqDays*86400000);guard+=1}
  return Math.max(1,count)
}
function reserveTargets(upcomingBills,today,nextPay,freqDays){
  return upcomingBills.map(b=>{
    const checks=paydaysThrough(b.date,today,nextPay,freqDays);
    const target=Math.round((Number(b.amount||0)/checks)*100)/100;
    return {...b,paychecksRemaining:checks,currentCheckReserve:target};
  })
}
function paycheckPlan(){
  const paycheck=clamp(data.paycheck,0,1e9), balance=clamp(data.currentBalance,0,1e9), available=paycheck+balance;
  const today=dateAtNoon(data.payDate)||new Date();today.setHours(12,0,0,0);
  const freqDays=data.profile?.payFrequency==='biweekly'?14:data.profile?.payFrequency==='monthly'?30:7;
  const nextPay=dateAtNoon(data.nextPayday)||new Date(today.getTime()+freqDays*86400000);
  const reserveEnd=new Date(nextPay.getTime()+clamp(data.profile?.reserveDays||14,7,31)*86400000);
  const windowStart=new Date(today);windowStart.setDate(windowStart.getDate()-14);
  const unpaid=billOccurrences(windowStart,reserveEnd).filter(b=>!b.paid).sort((a,b)=>(priorityRank[a.priority]-priorityRank[b.priority])||a.date.localeCompare(b.date));
  const dueNowBills=unpaid.filter(b=>dateAtNoon(b.date)<=nextPay);
  const upcomingRaw=unpaid.filter(b=>dateAtNoon(b.date)>nextPay&&dateAtNoon(b.date)<=reserveEnd);
  const upcomingBills=reserveTargets(upcomingRaw,today,nextPay,freqDays);
  const laterBills=[];
  const dueNow=dueNowBills.reduce((s,b)=>s+Number(b.amount||0),0);
  const upcomingTotal=upcomingBills.reduce((s,b)=>s+Number(b.amount||0),0);
  const reserveTarget=upcomingBills.reduce((s,b)=>s+Number(b.currentCheckReserve||0),0);
  const desiredSavings=Math.max(clamp(data.saveAmount,0,1e9),paycheck*clamp(data.savingsRate,0,100)/100);
  const desiredDebt=Math.min(clamp(data.debtGoal,0,1e9),clamp(data.debtAmount,0,1e9));

  // Priority order: immediate bills -> future-bill reserve -> savings -> extra debt -> safe spending.
  let remaining=available;
  const payNow=Math.min(remaining,dueNow);remaining-=payNow;
  const reserve=Math.min(remaining,reserveTarget);remaining-=reserve;
  const recommendedSavings=Math.min(remaining,desiredSavings);
  const chosenSavings=data.customSavings===null?recommendedSavings:Math.min(clamp(data.customSavings,0,1e9),remaining);
  remaining-=chosenSavings;
  const recommendedDebt=Math.min(remaining,desiredDebt);
  const chosenDebt=data.customDebt===null?recommendedDebt:Math.min(clamp(data.customDebt,0,1e9),remaining);
  remaining-=chosenDebt;
  const safeToSpend=Math.max(0,remaining-clamp(data.expenses,0,1e9));
  return {paycheck,balance,available,today,nextPay,reserveEnd,dueNowBills,upcomingBills,laterBills,dueNow,upcomingTotal,reserveTarget,desiredSavings,desiredDebt,payNow,reserve,savings:chosenSavings,debtPayment:chosenDebt,safeToSpend,shortfall:Math.max(0,dueNow-payNow),reserveShortfall:Math.max(0,reserveTarget-reserve)};
}
function calc(){const p=paycheckPlan(),bills=[...p.dueNowBills,...p.upcomingBills,...p.laterBills],billTotal=bills.filter(b=>!b.paid).reduce((s,b)=>s+Number(b.amount||0),0);let score=35;if(p.paycheck>0)score+=15;if(bills.length)score+=10;if(p.savings>0)score+=15;if(p.shortfall===0&&p.paycheck>0)score+=15;if(p.reserveShortfall===0&&p.upcomingBills.length)score+=5;if(data.approvedPlan)score+=5;const missionDone=Object.values(data.missions).filter(Boolean).length;return {...p,bills,billTotal,cash:p.safeToSpend,score:Math.min(score,100),progress:Math.round(missionDone/4*100),missionDone}}
function save(){data.lastUpdated=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));render()}
function billRows(host,bills){if(!host)return;host.replaceChildren();if(!bills.length){host.innerHTML='<div class="empty-copy">No bills in this payday window. Manage recurring bills in Financial Profile.</div>';return}bills.forEach(b=>{const row=document.createElement('div');row.className=`bill-row${b.paid?' paid':''}`;const btn=document.createElement('button');btn.className='check';btn.textContent=b.paid?'✓':'';btn.setAttribute('aria-label',b.paid?'Mark unpaid':'Mark paid');btn.onclick=()=>{const real=data.bills.find(x=>x.id===(b.parentId||b.id));if(real){real.paidOccurrences=Array.isArray(real.paidOccurrences)?real.paidOccurrences:[];const key=b.occurrenceDate||b.date;real.paidOccurrences=real.paidOccurrences.includes(key)?real.paidOccurrences.filter(x=>x!==key):[...real.paidOccurrences,key];data.approvedPlan=null;save()}};const name=document.createElement('span');name.innerHTML=`${b.name||'Bill'} <em class="priority ${b.priority}">${b.priority}</em>${b.autopay?' <em class="autopay">auto</em>':''}`;const amt=document.createElement('strong');amt.textContent=money(b.amount);const date=document.createElement('small');date.textContent=b.paid?'Paid':b.date?dateAtNoon(b.date).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'TBD';row.append(btn,name,amt,date);host.append(row)})}
function allocationRows(p){const host=$('allocationList');if(!host)return;host.replaceChildren();[['Bills due before next payday',p.payNow,p.shortfall?`${money(p.shortfall)} still unfunded`:`${p.dueNowBills.length} covered`],['Bills reserve — this check',p.reserve,p.reserveShortfall?`${money(p.reserveShortfall)} still needed`:`${p.upcomingBills.length} future bill${p.upcomingBills.length===1?'':'s'} protected`],['Move to savings',p.savings,`Target: ${money(p.desiredSavings)}`],['Extra debt payment',p.debtPayment,p.desiredDebt?`Goal: ${money(p.desiredDebt)}`:'Optional after priorities'],['TRUE safe to spend',p.safeToSpend,`Through ${p.nextPay.toLocaleDateString('en-US',{month:'short',day:'numeric'})}`]].forEach(([label,amount,note])=>{const row=document.createElement('div');row.className='allocation-row';row.innerHTML=`<div><strong>${label}</strong><small>${note}</small></div><b>${money(amount)}</b>`;host.append(row)})}
function reserveExplanation(p){
  if(!p.upcomingBills.length)return'';
  return p.upcomingBills.slice(0,4).map(b=>{
    const due=dateAtNoon(b.date)?.toLocaleDateString('en-US',{month:'short',day:'numeric'})||'soon';
    return `${b.name}: protect ${money(b.currentCheckReserve)} now toward ${money(b.amount)} due ${due} (${b.paychecksRemaining} paycheck${b.paychecksRemaining===1?'':'s'} including this one).`;
  }).join(' ')
}
function recommendation(p){
  if(!p.paycheck)return'Enter your check, next payday, and bills. I’ll prioritize the money automatically.';
  if(p.shortfall>0){const essentials=p.dueNowBills.filter(b=>b.priority==='essential').map(b=>b.name).slice(0,3).join(', ');return`This payday is ${money(p.shortfall)} short before future reserves. Protect ${essentials||'housing, utilities, transportation, and insurance'} first. Pause savings and extra debt payments if needed, reduce flexible spending to $0.00, and contact lower-priority billers before the due date.`}
  const why=reserveExplanation(p);
  if(p.reserveShortfall>0)return`Your immediate bills are covered, but this check cannot fully fund the ${money(p.reserveTarget)} future-bill reserve I recommend. Protect ${money(p.reserve)} now and keep flexible spending at ${money(p.safeToSpend)}. ${why} Savings and extra debt should stay behind this reserve until the gap is covered.`;
  if(p.upcomingBills.length)return`Your immediate bills are covered. I recommend protecting ${money(p.reserve)} from this check for future bills before treating the rest as available. ${why} Then move ${money(p.savings)} to savings${p.debtPayment?`, send ${money(p.debtPayment)} to debt`:''}. Your TRUE safe-to-spend amount is ${money(p.safeToSpend)}.`;
  return`Pay ${money(p.payNow)} now. No future-bill reserve is needed inside your current look-ahead window, so move ${money(p.savings)} to savings${p.debtPayment?`, send ${money(p.debtPayment)} to debt`:''}, and keep flexible spending at or below ${money(p.safeToSpend)} until payday.`
}
function experiment(p){if(!p.paycheck)return{title:'Build your first payday plan',text:'Add a paycheck and approve Dexx’s recommendation.',progress:0};if(!data.approvedPlan)return{title:'Approve the experiment',text:`Review the plan and protect ${money(p.savings)} for savings.`,progress:35};const target=Math.max(20,Math.min(p.safeToSpend*.2,75));return{title:`No-spend boost: save an extra ${money(target)}`,text:`Stay under ${money(p.safeToSpend)} in flexible spending and review your bills by Wednesday.`,progress:data.missions.spending&&data.missions.bills?100:data.missions.spending||data.missions.bills?70:50}}

function confidence(p){let level='LOW',pct=25,text='Complete your profile and enter a paycheck.';if(p.paycheck&&p.shortfall===0){level='MEDIUM';pct=65;text='Immediate bills are covered, but review reserves and savings.'}if(p.paycheck&&p.shortfall===0&&p.reserveShortfall===0&&p.savings>0){level='HIGH';pct=100;text='Bills, upcoming reserves and savings are protected.'}return{level,pct,text}}
function renderTimeline(c){const host=$('financialTimeline');if(!host)return;host.replaceChildren();const events=[];if(c.paycheck)events.push({date:c.today,label:'Paycheck received',amount:c.paycheck,type:'income'});if(c.savings)events.push({date:c.today,label:'Move to savings',amount:-c.savings,type:'saving'});c.dueNowBills.forEach(b=>events.push({date:dateAtNoon(b.date)||c.today,label:b.name,amount:-Number(b.amount||0),type:'bill'}));c.upcomingBills.forEach(b=>events.push({date:dateAtNoon(b.date),label:`Reserve: ${b.name}`,amount:-Number(b.amount||0),type:'reserve'}));events.push({date:c.nextPay,label:'Next payday',amount:0,type:'payday'});events.sort((a,b)=>a.date-b.date).slice(0,8).forEach(e=>{const row=document.createElement('div');row.className='timeline-row';row.innerHTML=`<div><strong>${e.date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</strong><span>${e.label}</span></div><b>${e.amount?money(e.amount):'Coming up'}</b>`;host.append(row)});if(!events.length)host.innerHTML='<div class="empty-copy">Add your paycheck and bills to build the week ahead.</div>'}
function renderProfile(){const p=data.profile||DEFAULTS.profile;const map={profileName:data.researcherName||'Rob',payFrequency:p.payFrequency,paydayDay:String(p.paydayDay??5),incomePattern:p.incomePattern,recurringBillCount:p.recurringBillCount,financialStrategy:p.financialStrategy,profileSavingsRate:data.savingsRate||10,reserveDays:String(p.reserveDays||14)};Object.entries(map).forEach(([id,v])=>{if($(id))$(id).value=v});const fields=[data.researcherName,p.payFrequency,p.incomePattern,p.recurringBillCount,p.financialStrategy,data.savingsRate,p.reserveDays],pct=Math.round(fields.filter(v=>v!==''&&v!==null&&v!==undefined).length/fields.length*100);if($('profileCompletion'))$('profileCompletion').textContent=`${pct}% complete`;if($('profileReady'))$('profileReady').textContent=pct===100?'Ready for Payday Mode':'Needs setup';if($('profileSummary'))$('profileSummary').innerHTML=`<div><span>PAY SCHEDULE</span><strong>${p.payFrequency||'weekly'}</strong></div><div><span>CHECK AMOUNT</span><strong>${p.incomePattern==='variable'?'Variable':'Steady'}</strong></div><div><span>BILLS SAVED</span><strong>${billDefinitions().length} saved</strong></div><div><span>STRATEGY</span><strong>${p.financialStrategy||'balanced'}</strong></div>`;renderBillManager()}
function resetBillManagerForm(){if(!$('billManagerForm'))return;$('managerBillId').value='';$('managerBillName').value='';$('managerBillAmount').value='';$('managerBillDate').value='';$('managerBillFrequency').value='monthly';$('managerBillPriority').value='essential';$('managerBillAutopay').checked=false;$('saveManagedBill').textContent='SAVE RECURRING BILL';$('cancelBillEdit').hidden=true}
function renderBillManager(){const host=$('managedBills');if(!host)return;const defs=billDefinitions(),estimate=Number(data.profile?.recurringBillCount)||0;if($('billManagerProgress'))$('billManagerProgress').textContent=`${defs.length} bill${defs.length===1?'':'s'} saved`;if($('billManagerEstimate'))$('billManagerEstimate').textContent=estimate?`Profile estimate: ${estimate} recurring bill${estimate===1?'':'s'}. This is a planning estimate, not a limit.`:'Add as many recurring bills as you need. There is no bill limit.';host.replaceChildren();if(!defs.length){host.innerHTML='<div class="empty-copy">No recurring bills saved yet. Add your first bill above.</div>';return}defs.sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).forEach(b=>{const card=document.createElement('article');card.className='managed-bill';const freq={monthly:'Monthly',weekly:'Weekly',biweekly:'Every 2 weeks',once:'One time'}[b.frequency]||b.frequency;card.innerHTML=`<div class="managed-bill-main"><div><strong>${b.name}</strong><span>${freq} · ${b.priority}${b.autopay?' · Autopay':''}</span></div><b>${money(b.amount)}</b></div><div class="managed-bill-meta"><span>Next due ${b.dueDate?dateAtNoon(b.dueDate).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'TBD'}</span><div><button type="button" data-edit-bill="${b.id}">Edit</button><button type="button" class="danger-link" data-delete-bill="${b.id}">Delete</button></div></div>`;host.append(card)})}
function renderHistory(){const host=$('planHistory');if(!host)return;host.replaceChildren();const list=[...data.paycheckHistory].reverse().slice(0,6);if(!list.length){host.innerHTML='<div class="empty-copy">Approved plans will appear here.</div>';return}list.forEach(h=>{const row=document.createElement('article');row.className='history-row';row.innerHTML=`<div><strong>${money(h.paycheck)} payday</strong><small>${new Date(h.approvedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</small></div><span>Saved ${money(h.savings)} · Spend ${money(h.safeToSpend)}</span>`;host.append(row)})}
function render(){const c=calc(),hour=new Date().getHours();$('greeting').textContent=`GOOD ${hour<12?'MORNING':hour<17?'AFTERNOON':'EVENING'}, ${(data.researcherName||'ROB').toUpperCase()} 👋`;$('healthScore').textContent=c.score;$('scoreRing').style.setProperty('--score',c.score);$('healthMessage').textContent=c.score>=80?'Your payday plan is fully protected.':c.score>=60?'Your plan is gaining strength.':'Complete Payday Mode to improve your score.';$('cashAvailable').textContent=money(c.safeToSpend);$('billsWeek').textContent=money(c.payNow);$('savingsTotal').textContent=money(c.savings);$('savingsPageTotal').textContent=money(c.savings);$('debtRemaining').textContent=money(data.debtAmount);$('missionCount').textContent=`${c.missionDone} / 4`;$('progressText').textContent=`${c.progress}%`;$('progressBar').style.width=`${c.progress}%`;$('dexxObservation').textContent=recommendation(c);const conf=confidence(c);if($('confidenceLabel'))$('confidenceLabel').textContent=conf.level;if($('confidenceText'))$('confidenceText').textContent=conf.text;if($('confidenceBar'))$('confidenceBar').style.width=`${conf.pct}%`;renderTimeline(c);renderProfile();document.querySelectorAll('[data-mission]').forEach(x=>x.checked=!!data.missions[x.dataset.mission]);billRows($('billList'),c.bills.filter(b=>!b.paid).slice(0,4));billRows($('allBills'),c.bills);
  ['paycheck','currentBalance','saveAmount','debtAmount','debtGoal','savingsRate'].forEach(id=>{if($(id))$(id).value=data[id]||(id==='savingsRate'?10:'')});if($('payDate'))$('payDate').value=data.payDate||iso(new Date());if($('nextPayday'))$('nextPayday').value=data.nextPayday||'';
  if($('planPayNow')){$('planPayNow').textContent=money(c.payNow);$('planReserve').textContent=money(c.reserve);$('planSavings').textContent=money(c.savings);$('planDebt').textContent=money(c.debtPayment);$('planSpend').textContent=money(c.safeToSpend);$('planStatus').textContent=c.shortfall?'Needs attention':data.approvedPlan?'Approved':c.paycheck?'Plan ready':'Ready';$('dexxPlanText').textContent=recommendation(c);const total=c.available||1;[['allocBills',c.payNow],['allocReserve',c.reserve],['allocSavings',c.savings],['allocDebt',c.debtPayment],['allocSpend',c.safeToSpend]].forEach(([id,val])=>$(id).style.width=`${Math.max(0,val/total*100)}%`);allocationRows(c);$('customSavings').value=data.customSavings??'';$('customDebt').value=data.customDebt??'';const step=!c.paycheck?1:!c.bills.length?2:!data.approvedPlan?4:5;$('workflowStatus').textContent=`Step ${step} of 5`;$('workflowCopy').textContent=step===1?'Enter your check and payday dates.':step===2?'Add and confirm every bill coming before and after payday.':step===4?'Review Dexx’s recommendation and adjust only if needed.':'Plan approved. Track the experiment until next payday.';document.querySelectorAll('.step-track i').forEach((x,i)=>x.classList.toggle('active',i<step));const ex=experiment(c);$('experimentTitle').textContent=ex.title;$('experimentText').textContent=ex.text;$('experimentBar').style.width=`${ex.progress}%`;$('experimentProgress').textContent=`${ex.progress}% complete`;renderHistory()}}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));history.replaceState(null,'','#'+id);scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){e.preventDefault();show(go.dataset.go)}const q=e.target.closest('[data-question]');if(q){const c=calc(),answers={score:`Your score is ${c.score}. Cover immediate bills, protect ${money(c.savings)} in savings, and stay within ${money(c.safeToSpend)}.`,spending:`Your safe-to-spend amount is ${money(c.safeToSpend)} through ${c.nextPay.toLocaleDateString('en-US',{month:'short',day:'numeric'})}.`,challenge:experiment(c).text,saving:`I recommend ${money(c.savings)} this payday. Increase it only after immediate and upcoming bills are protected.`};$('dexxReply').textContent=answers[q.dataset.question]}});
document.querySelectorAll('[data-mission]').forEach(x=>x.addEventListener('change',()=>{data.missions[x.dataset.mission]=x.checked;save()}));
$('budgetForm').addEventListener('submit',e=>{e.preventDefault();data.paycheck=clamp($('paycheck').value,0,1e9);data.currentBalance=clamp($('currentBalance').value,0,1e9);data.payDate=$('payDate').value;data.nextPayday=$('nextPayday').value;data.savingsRate=clamp($('savingsRate').value,0,100);data.saveAmount=clamp($('saveAmount').value,0,1e9);data.debtAmount=clamp($('debtAmount').value,0,1e9);data.debtGoal=clamp($('debtGoal').value,0,1e9);const name=$('billName').value.trim(),date=$('billDate').value,amount=clamp($('billAmount').value,0,1e9);if(name||date||amount)data.bills.push({id:crypto.randomUUID?crypto.randomUUID():`bill-${Date.now()}`,name:name||'Upcoming bill',dueDate:date,date,amount,priority:$('billPriority').value,frequency:$('billFrequency').value,autopay:$('billAutopay').checked,paidOccurrences:[]});data.customSavings=null;data.customDebt=null;data.approvedPlan=null;data.missions.bills=data.bills.length>0;save();$('billName').value='';$('billDate').value='';$('billAmount').value='';$('billAutopay').checked=false;$('formStatus').textContent='Dexx rebuilt your payday plan. Review it above, then approve the experiment.'});
$('billManagerForm')?.addEventListener('submit',e=>{e.preventDefault();const id=$('managerBillId').value,name=$('managerBillName').value.trim(),amount=clamp($('managerBillAmount').value,0,1e9),dueDate=$('managerBillDate').value;if(!name||!amount||!dueDate){$('billManagerStatus').textContent='Add the bill name, amount, and next due date.';return}const existing=id?data.bills.find(b=>b.id===id):null;const record={id:id||(crypto.randomUUID?crypto.randomUUID():`bill-${Date.now()}`),name,amount,dueDate,date:dueDate,priority:$('managerBillPriority').value,frequency:$('managerBillFrequency').value,autopay:$('managerBillAutopay').checked,paidOccurrences:existing?.paidOccurrences||[]};if(existing)Object.assign(existing,record);else data.bills.push(record);if(!existing&&data.bills.length>Number(data.profile?.recurringBillCount||0)){data.profile=data.profile||structuredClone(DEFAULTS.profile);data.profile.recurringBillCount=data.bills.length}data.missions.bills=data.bills.length>0;data.approvedPlan=null;save();$('billManagerStatus').textContent=existing?'Bill updated. Dexx recalculated your payday plan.':'Bill saved. Dexx will use it automatically every payday.';resetBillManagerForm()});
$('cancelBillEdit')?.addEventListener('click',()=>{resetBillManagerForm();$('billManagerStatus').textContent='Edit canceled.'});
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-bill]');if(edit){const b=data.bills.find(x=>x.id===edit.dataset.editBill);if(!b)return;$('managerBillId').value=b.id;$('managerBillName').value=b.name;$('managerBillAmount').value=b.amount;$('managerBillDate').value=b.dueDate||b.date||'';$('managerBillFrequency').value=b.frequency||'monthly';$('managerBillPriority').value=b.priority||'important';$('managerBillAutopay').checked=!!b.autopay;$('saveManagedBill').textContent='UPDATE BILL';$('cancelBillEdit').hidden=false;$('billManagerStatus').textContent=`Editing ${b.name}.`;if(location.hash!=='#profile')show('profile');setTimeout(()=>$('managerBillName').scrollIntoView({behavior:'smooth',block:'center'}),80)}const del=e.target.closest('[data-delete-bill]');if(del){const b=data.bills.find(x=>x.id===del.dataset.deleteBill);if(b&&confirm(`Delete ${b.name}?`)){data.bills=data.bills.filter(x=>x.id!==b.id);data.approvedPlan=null;data.missions.bills=data.bills.length>0;save();$('billManagerStatus').textContent=`${b.name} deleted.`}}});
$('customSavings').addEventListener('change',()=>{data.customSavings=$('customSavings').value===''?null:clamp($('customSavings').value,0,1e9);data.approvedPlan=null;save()});$('customDebt').addEventListener('change',()=>{data.customDebt=$('customDebt').value===''?null:clamp($('customDebt').value,0,1e9);data.approvedPlan=null;save()});
$('approvePlan').onclick=()=>{const c=calc();if(!c.paycheck){$('approvalStatus').textContent='Enter your paycheck first.';return}const snapshot={id:`plan-${Date.now()}`,approvedAt:new Date().toISOString(),paycheck:c.paycheck,balance:c.balance,payDate:data.payDate,nextPayday:data.nextPayday,payNow:c.payNow,reserve:c.reserve,reserveTarget:c.reserveTarget,reserveDetails:c.upcomingBills.map(b=>({name:b.name,amount:b.amount,date:b.date,currentCheckReserve:b.currentCheckReserve,paychecksRemaining:b.paychecksRemaining})),savings:c.savings,debtPayment:c.debtPayment,safeToSpend:c.safeToSpend,shortfall:c.shortfall,bills:c.dueNowBills.map(b=>({name:b.name,amount:b.amount,date:b.date,priority:b.priority}))};data.approvedPlan=snapshot;data.paycheckHistory.push(snapshot);data.missions.friday=true;data.missions.saving=c.savings>0;data.missions.bills=c.bills.length>0;save();$('approvalStatus').textContent='Payday plan approved and saved. Your weekly experiment is active.'};
$('clearBills').onclick=()=>{if(confirm('Clear all saved bills?')){data.bills=[];data.billName='';data.billDate='';data.billAmount=0;data.approvedPlan=null;save()}};$('clearHistory').onclick=()=>{if(confirm('Clear paycheck plan history?')){data.paycheckHistory=[];data.approvedPlan=null;save()}};
$('chatForm').addEventListener('submit',e=>{e.preventDefault();const text=$('chatInput').value.trim();if(!text)return;const c=calc();$('dexxReply').textContent=`Based on this payday, cover ${money(c.payNow)} now, protect ${money(c.reserve)} for upcoming bills, save ${money(c.savings)}, pay ${money(c.debtPayment)} toward debt, and limit flexible spending to ${money(c.safeToSpend)}.`;$('chatInput').value=''});
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const type=b.dataset.action;if(type==='income'){show('budget');setTimeout(()=>$('paycheck').focus(),200);return}const raw=prompt('Expense amount');const val=clamp(raw,0,1e9);if(!val)return;data.expenses+=val;save();show('laboratory')});
const initial=location.hash.slice(1);show(['laboratory','budget','profile','credit','savings','more','dexx'].includes(initial)?initial:'laboratory');render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn));

$('profileForm')?.addEventListener('submit',e=>{e.preventDefault();data.researcherName=$('profileName').value.trim()||'Rob';data.profile={payFrequency:$('payFrequency').value,paydayDay:Number($('paydayDay').value),incomePattern:$('incomePattern').value,recurringBillCount:clamp($('recurringBillCount').value,0,99),financialStrategy:$('financialStrategy').value,reserveDays:clamp($('reserveDays').value,7,31)};data.savingsRate=clamp($('profileSavingsRate').value,0,100);save();$('profileStatus').textContent='Financial Profile saved. Dexx will use it for every payday plan.'});
